### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by ankerbachryhl** [polilang/poli#1]
The language dont compile and there is no documentation. I am unsatisfied :( 👎

**Comment by evolbug** [comment]
it's just started out :D literally about a week old. we are making this from scratch :)

**Comment by ankerbachryhl** [comment]
Bad service. This is unacceptable!

**Comment by ankerbachryhl** [comment]
:( :( :(

**Comment by evolbug** [comment]
how dare you :(

**Comment by ankerbachryhl** [comment]
Jk I think it is nice 👍

**Comment by evolbug** [comment]
:) you can download it and run it using Rust's `cargo run`
so far there is just tokenizer and we have started work on parsing
